version: '3.8'

services:
    backend:
        build: ./backend
        ports:
        - "8000:8000"
        environment:
        - DJANGO_SETTINGS_MODULE=core.settings.base
        volumes:
        - ./backend:/app
        command: >
            sh -c "python manage.py migrate backend 0017 &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
        restart: unless-stopped

    frontend:
        build: ./frontend
        ports:
        - "3000:3000"
        volumes:
        - ./frontend:/app
        - /app/node_modules
        environment:
        - NODE_ENV=development
        - CHOKIDAR_USEPOLLING=true
        depends_on:
        - backend
        restart: unless-stopped